= Asciidoctor Project Site
// Settings:
ifdef::env-github[]
:badges:
endif::[]
// URIs:
:uri-letsencrypt: https://letsencrypt.org
:uri-letsencrypt-article: https://fedoramagazine.org/letsencrypt-now-available-fedora/
:uri-awestruct: https://github.com/awestruct/awestruct
:uri-netlify: https://www.netlify.com
:uri-netlify-deploys: https://app.netlify.com/sites/asciidoctor/deploys
:uri-travis-builds: https://travis-ci.org/asciidoctor/asciidoctor.org

ifdef::badges[]
image:https://secure.travis-ci.org/asciidoctor/asciidoctor.org.svg?branch=master[Build Status,link={uri-travis-builds}]
image:https://www.netlify.com/img/global/badges/netlify-dark.svg[Deploy Status,45,20,link={uri-netlify-deploys}]
endif::[]

这是 https://asciidoctor.org[Asciidoctor] 项目的网站。
该网站由 AsciiDoc 组成,  https://foundation.zurb.com/sites/docs/v/4.3.2[Foundation 4] 设计,  {uri-awestruct}[Awestruct] 制作, 在 {uri-netlify}[Netlify] 上托管。

有关如何安装 Awestruct 及其依赖项的说明， 请参阅下面的 <<安装 Awestruct>> 部分。

== 本地预览网站

要在本地预览站点，只需运行默认的rake构建任务:

 $ rake

默认的 rake 构建任务是 `preview`，所以你可以输入:

 $ rake preview

`preview` 任务只是在开发模式下直接调用 Awestruct 的一种简短方式:

 $ awestruct -d

现在访问 http://localhost:4242 预览该站点。

要从一个干净的状态重建站点，将 `--force` 标志传递到 `preview` 任务:

 $ rake preview[--force]

您可以使用前面命令中的语法将任何标志传递给 Awestruct 。

如果你只是想生成网站，运行:

 $ rake gen

////
=== Set the JavaScript runtime

If you're building the site on Linux and Awestruct fails to locate a JavaScript runtime, you can either:

. install a node.js package or
. set the following environment variable in your shell profile scripts (e.g., `~/.bash_profile`):

 $ export EXECJS_RUNTIME=SpiderMonkey
////

== 添加和提交文件

添加新文件(如新的博客条目或图像):

 $ git add news/news-slug.adoc

或者目录中出现的所有新文件(它只影响新文件，跳过已经提交的文件)

 $ git add news/

提交所有标记为提交的文件，包括刚刚添加的新文件:

 $ git commit -m '你的信息在这里'

提交所有已更改的文件，即使没有标记为提交:

 $ git commit -a -m '你的信息在这里'

确保没有文件是 "untracked" 或 "modified":

 $ git status

您应该看到:

[.output]
....
nothing to commit (working directory clean)
....

现在可以部署了。

////
== Deploy the site to GitHub Pages

The following commands will push changes (`git push`), clean build the site (`--force -g`) using the production profile (`-P production`), then deploy it to github pages (`--deploy`):

 $ git push &&
   awestruct -P production --force -g --deploy

Or simply run the prepared rake build task (to deploy locally):

 $ rake deploy

Or just push and let {uri-travis-builds}[Travis CI] do the work of deploying the site:

 $ rake push

If you want to push without triggering a publish, add the following to the commit message:

....
[ci skip]
....
////

== 安装 Awestruct

首先, 安装 https://rvm.io[RVM] 。
相信我 。

 $ curl -#L https://get.rvm.io | bash -s stable --ruby

接下来，为让 Asciidoctor 站点工作，设置 RVM gemset :

 $ rvm use 2.4 --create

此时，您可以直接安装Awestruct，但是由于站点构建有一些额外的依赖项，最好让bundler来处理安装。
Bundler还将确保您在运行Awestruct时使用了每个gem的正确版本。

 $ bundle --path=.bundle/gems

你现在 Awestruct !

== 主机

本网站位于[Netlify]，域名为 asciidoctor.org。
它由帐户docbot[at]asciidoctor[dot]org 和其他 Asciidoctor 管理员管理。

=== 部署

Netlify还负责生成和部署站点。
部署是通过git存储库主分支上的webhook触发的。
部署作业执行以下命令:

 $ rake deploy:netlify

Ruby的版本是使用Netlify配置中的环境变量设置的。

asciidoctor.org 的部署日志可以在 {uri-netlify-deploys} 中查看。

=== DNS

有两个DNS记录指向Netlify服务器的asciidoctor.org和www.asciidoctor.org:

 @ 3600 IN A 104.198.14.52
 www 3600 IN CNAME asciidoctor.netlify.com.

Netlify服务器自动设置从www.asciidoctor.org指向asciidoctor.org的重定向。

=== TLS 证书 (https)

asciidoctor.org 和 www.asciidoctor.org 的 TLS 证书是使用 {uri-letsencrypt}[Let's Encrypt] 颁发的，由 {uri-netlify}[Netlify] 管理 。

使用以下方法验证证书是否有效:

 $ curl -vI https://asciidoctor.org

在 "`Server certificate`" 部分中查找  `CN=asciidoctor.org`  。

感谢 Netlify，证书将在接近到期日期时自动重新生成 。
